#!/bin/sh

set -e
set -x

GENTLE=../../../gentle/gentle
GRTS=../../../gentle/grts.o
REFLEX=../../../reflex/reflex
LIB=../../../lib
LEX=lex
YACC=yacc
CC=cc

$GENTLE c.g

$REFLEX

$LEX gen.l

$YACC gen.y

$CC -o c \
   c.c \
   lex.yy.c \
   y.tab.c \
   $LIB/idents.o \
   $LIB/errmsg.o \
   $LIB/main.o \
   $GRTS

./c testfile
